spring:
  datasource:
    data: classpath:data.sql
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create-drop
    h2:
      console:
        enabled: true
  jwt:
    secret: martintest!@341!#3
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
